server:
  port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/assigment?useSSL=false
        username: admin
        password: admin
    
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                generate_statistics: false
                hibernate.format_sql: false
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 
              clientSecret: 
              redirectUriTemplate: "http://localhost:8080/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
app:
  auth:
    tokenSecret: assigment564et3e23shdue
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect
   
